// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VFR3D.Domain.ValueObjects.Flights;
using VFR3D.Domain.ValueObjects.WeightBalance;
using VFR3D.Infrastructure.Data;

#nullable disable

namespace VFR3D.Infrastructure.Migrations
{
    [DbContext(typeof(VFR3DDbContext))]
    [Migration("20260215033634_RemoveReferenceDataTables")]
    partial class RemoveReferenceDataTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VFR3D.Domain.Entities.Aircraft", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AircraftHome")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("aircraft_home");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("aircraft_type");

                    b.Property<string>("AirspeedUnits")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("airspeed_units");

                    b.Property<string>("CallSign")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("call_sign");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Color2")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("color2");

                    b.Property<string>("Color3")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("color3");

                    b.Property<string>("Color4")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("color4");

                    b.Property<int?>("DefaultCruiseAltitude")
                        .HasColumnType("integer")
                        .HasColumnName("default_cruise_altitude");

                    b.Property<double?>("GlideRatio")
                        .HasColumnType("double precision")
                        .HasColumnName("glide_ratio");

                    b.Property<int?>("GlideSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("glide_speed");

                    b.Property<string>("LengthUnits")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("length_units");

                    b.Property<int?>("MaxCeiling")
                        .HasColumnType("integer")
                        .HasColumnName("max_ceiling");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("primary_color");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("serial_number");

                    b.Property<string>("TailNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tail_number");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "TailNumber")
                        .IsUnique();

                    b.ToTable("aircraft", (string)null);
                });

            modelBuilder.Entity("VFR3D.Domain.Entities.AircraftDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AircraftId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aircraft_id");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("blob_name");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "AircraftId");

                    b.ToTable("aircraft_documents", (string)null);
                });

            modelBuilder.Entity("VFR3D.Domain.Entities.AircraftPerformanceProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AircraftId")
                        .HasColumnType("text")
                        .HasColumnName("aircraft_id");

                    b.Property<int>("ClimbFpm")
                        .HasColumnType("integer")
                        .HasColumnName("climb_fpm");

                    b.Property<double>("ClimbFuelBurn")
                        .HasColumnType("double precision")
                        .HasColumnName("climb_fuel_burn");

                    b.Property<int>("ClimbTrueAirspeed")
                        .HasColumnType("integer")
                        .HasColumnName("climb_true_airspeed");

                    b.Property<double>("CruiseFuelBurn")
                        .HasColumnType("double precision")
                        .HasColumnName("cruise_fuel_burn");

                    b.Property<int>("CruiseTrueAirspeed")
                        .HasColumnType("integer")
                        .HasColumnName("cruise_true_airspeed");

                    b.Property<int>("DescentFpm")
                        .HasColumnType("integer")
                        .HasColumnName("descent_fpm");

                    b.Property<double>("DescentFuelBurn")
                        .HasColumnType("double precision")
                        .HasColumnName("descent_fuel_burn");

                    b.Property<int>("DescentTrueAirspeed")
                        .HasColumnType("integer")
                        .HasColumnName("descent_true_airspeed");

                    b.Property<double>("FuelOnBoardGals")
                        .HasColumnType("double precision")
                        .HasColumnName("fuel_on_board_gals");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("profile_name");

                    b.Property<double>("SttFuelGals")
                        .HasColumnType("double precision")
                        .HasColumnName("stt_fuel_gals");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ProfileName")
                        .IsUnique();

                    b.ToTable("aircraft_performance", (string)null);
                });

            modelBuilder.Entity("VFR3D.Domain.Entities.Flight", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AircraftId")
                        .HasColumnType("text")
                        .HasColumnName("aircraft_id");

                    b.Property<string>("AircraftPerformanceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aircraft_performance_id");

                    b.Property<List<string>>("AirspaceGlobalIds")
                        .HasColumnType("jsonb")
                        .HasColumnName("airspace_global_ids");

                    b.Property<string>("Auth0UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth0_user_id");

                    b.Property<double>("AverageWindComponent")
                        .HasColumnType("double precision")
                        .HasColumnName("average_wind_component");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_time");

                    b.Property<List<NavlogLeg>>("Legs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("legs");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<List<string>>("ObstacleOasNumbers")
                        .HasColumnType("jsonb")
                        .HasColumnName("obstacle_oas_numbers");

                    b.Property<int>("PlannedCruisingAltitude")
                        .HasColumnType("integer")
                        .HasColumnName("planned_cruising_altitude");

                    b.Property<string>("RelatedFlightId")
                        .HasColumnType("text")
                        .HasColumnName("related_flight_id");

                    b.Property<List<string>>("SpecialUseAirspaceGlobalIds")
                        .HasColumnType("jsonb")
                        .HasColumnName("special_use_airspace_global_ids");

                    b.Property<List<string>>("StateCodesAlongRoute")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state_codes_along_route");

                    b.Property<double>("TotalFuelUsed")
                        .HasColumnType("double precision")
                        .HasColumnName("total_fuel_used");

                    b.Property<double>("TotalRouteDistance")
                        .HasColumnType("double precision")
                        .HasColumnName("total_route_distance");

                    b.Property<double>("TotalRouteTimeHours")
                        .HasColumnType("double precision")
                        .HasColumnName("total_route_time_hours");

                    b.Property<List<Waypoint>>("Waypoints")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("waypoints");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("AircraftPerformanceId");

                    b.HasIndex("Auth0UserId");

                    b.HasIndex("Auth0UserId", "Name");

                    b.ToTable("flights", (string)null);
                });

            modelBuilder.Entity("VFR3D.Domain.Entities.WeightBalanceCalculation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<string>("EnvelopeId")
                        .HasColumnType("text")
                        .HasColumnName("envelope_id");

                    b.Property<List<CgEnvelopePoint>>("EnvelopeLimits")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("envelope_limits");

                    b.Property<string>("EnvelopeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("envelope_name");

                    b.Property<string>("FlightId")
                        .HasColumnType("text")
                        .HasColumnName("flight_id");

                    b.Property<double?>("FuelBurnGallons")
                        .HasColumnType("double precision")
                        .HasColumnName("fuel_burn_gallons");

                    b.Property<bool>("IsStandalone")
                        .HasColumnType("boolean")
                        .HasColumnName("is_standalone");

                    b.Property<WeightBalanceCgResult>("LandingResult")
                        .HasColumnType("jsonb")
                        .HasColumnName("landing_result");

                    b.Property<List<StationLoad>>("LoadedStations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("loaded_stations");

                    b.Property<List<StationBreakdown>>("StationBreakdown")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("station_breakdown");

                    b.Property<WeightBalanceCgResult>("TakeoffResult")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("takeoff_result");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<List<string>>("Warnings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("warnings");

                    b.Property<Guid>("WeightBalanceProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("weight_balance_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("FlightId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("WeightBalanceProfileId");

                    b.HasIndex("UserId", "IsStandalone");

                    b.ToTable("weight_balance_calculations", (string)null);
                });

            modelBuilder.Entity("VFR3D.Domain.Entities.WeightBalanceProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AircraftId")
                        .HasColumnType("text")
                        .HasColumnName("aircraft_id");

                    b.Property<string>("ArmUnits")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arm_units");

                    b.Property<List<CgEnvelope>>("CgEnvelopes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cg_envelopes");

                    b.Property<string>("DatumDescription")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("datum_description");

                    b.Property<double>("EmptyWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("empty_weight");

                    b.Property<double>("EmptyWeightArm")
                        .HasColumnType("double precision")
                        .HasColumnName("empty_weight_arm");

                    b.Property<string>("LoadingGraphFormat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("loading_graph_format");

                    b.Property<List<LoadingStation>>("LoadingStations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("loading_stations");

                    b.Property<double?>("MaxLandingWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("max_landing_weight");

                    b.Property<double?>("MaxRampWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("max_ramp_weight");

                    b.Property<double>("MaxTakeoffWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("max_takeoff_weight");

                    b.Property<double?>("MaxZeroFuelWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("max_zero_fuel_weight");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("profile_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("WeightUnits")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("weight_units");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ProfileName")
                        .IsUnique();

                    b.ToTable("weight_balance_profiles", (string)null);
                });

            modelBuilder.Entity("VFR3D.Domain.Entities.AircraftDocument", b =>
                {
                    b.HasOne("VFR3D.Domain.Entities.Aircraft", "Aircraft")
                        .WithMany("Documents")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("VFR3D.Domain.Entities.AircraftPerformanceProfile", b =>
                {
                    b.HasOne("VFR3D.Domain.Entities.Aircraft", "Aircraft")
                        .WithMany("PerformanceProfiles")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("VFR3D.Domain.Entities.Flight", b =>
                {
                    b.HasOne("VFR3D.Domain.Entities.Aircraft", "Aircraft")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VFR3D.Domain.Entities.AircraftPerformanceProfile", "AircraftPerformanceProfile")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftPerformanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("AircraftPerformanceProfile");
                });

            modelBuilder.Entity("VFR3D.Domain.Entities.WeightBalanceCalculation", b =>
                {
                    b.HasOne("VFR3D.Domain.Entities.Flight", "Flight")
                        .WithOne("WeightBalanceCalculation")
                        .HasForeignKey("VFR3D.Domain.Entities.WeightBalanceCalculation", "FlightId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VFR3D.Domain.Entities.WeightBalanceProfile", "WeightBalanceProfile")
                        .WithMany()
                        .HasForeignKey("WeightBalanceProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("WeightBalanceProfile");
                });

            modelBuilder.Entity("VFR3D.Domain.Entities.WeightBalanceProfile", b =>
                {
                    b.HasOne("VFR3D.Domain.Entities.Aircraft", "Aircraft")
                        .WithMany("WeightBalanceProfiles")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("VFR3D.Domain.Entities.Aircraft", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Flights");

                    b.Navigation("PerformanceProfiles");

                    b.Navigation("WeightBalanceProfiles");
                });

            modelBuilder.Entity("VFR3D.Domain.Entities.AircraftPerformanceProfile", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("VFR3D.Domain.Entities.Flight", b =>
                {
                    b.Navigation("WeightBalanceCalculation");
                });
#pragma warning restore 612, 618
        }
    }
}
